answer(river(loc_2(stateid('colorado'))))
answer(count(state(low_point_2(lower_2(low_point_1(stateid('alabama')))))))
answer(count(river(loc_2(stateid('california')))))
answer(state(next_to_2(stateid('utah'))))
answer(elevation_1(placeid('mount mckinley')))
answer(elevation_1(highest(place(loc_2(countryid('usa'))))))
answer(elevation_1(highest(place(loc_2(stateid('alabama'))))))
answer(size(stateid('alaska')))
answer(size(stateid('texas')))
answer(len(river(riverid('colorado'))))
